# Alacritty Configuration for Hyprland

[env]
TERM = "xterm-256color"

[window]
# Window dimensions (changes require restart)
dimensions = { columns = 120, lines = 30 }

# Window padding (changes require restart)
padding = { x = 10, y = 10 }

# Spread additional padding evenly around the terminal content
dynamic_padding = true

# Window decorations
decorations = "full"

# Background opacity
opacity = 0.9

# Startup mode (Windowed, Maximized, Fullscreen)
startup_mode = "Windowed"

[scrolling]
# Maximum number of lines in the scrollback buffer
history = 10000

# Scrolling distance multiplier
multiplier = 3

[font]
# Normal font face
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

# Font size
size = 11.0

[colors]
# Default colors
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

# Cursor colors
[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

# Normal colors
[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

# Bright colors
[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[cursor]
# Cursor style
style = { shape = "Block", blinking = "Off" }

# Vi mode cursor style
vi_mode_style = { shape = "Block", blinking = "Off" }

[selection]
# This string contains all characters that are used as separators for "semantic words" in Alacritty
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"

# When set to true, selected text will be copied to the primary clipboard
save_to_clipboard = true

[mouse]

# If this is true, the cursor is temporarily hidden when typing
hide_when_typing = true

# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"
